Vector Addition, Subtraction and Multiplication

Addition

In [1]:
import numpy as np
x = np.array([1,2,3])
print(x)
y = np.array([4,5,6])
print(y)
z = x+y
print(z)

[1 2 3]
[4 5 6]
[5 7 9]


Subtraction

In [2]:
a= y-x
print(a)

[3 3 3]


Dot Multiplication

In [7]:
b=x.dot(y)
print(b)

32


Matrix Operation

Addition

In [14]:
mat1 = np.array(([1,2],[4,5]))
print(mat1)
mat2 = np.array(([3,4],[1,6]))
print(mat2)

[[1 2]
 [4 5]]
[[3 4]
 [1 6]]


In [15]:
mat_add = mat1+mat2
print(mat_add)

[[ 4  6]
 [ 5 11]]


Subtraction

In [16]:
mat_sub = mat2-mat1
print(mat_sub)

[[ 2  2]
 [-3  1]]


Dot Multiplication

In [17]:
mat_mul = mat1.dot(mat2)
print(mat_mul)

[[ 5 16]
 [17 46]]
